# Generated by Django 4.0.3 on 2022-03-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratory',
            name='image',
            field=models.ImageField(upload_to='laboratory/images'),
        ),
    ]
