# Generated by Django 4.0.3 on 2022-03-30 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0002_alter_laboratory_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratory',
            name='analyzes',
        ),
    ]
