# Generated by Django 4.0.3 on 2023-02-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0004_analyze_user'),
        ('laboratory', '0003_remove_laboratory_analyzes'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory',
            name='analyze_laboratory',
            field=models.ManyToManyField(to='analyze.analyze'),
        ),
    ]
