# Generated by Django 4.0.3 on 2022-03-10 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Analyze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('preparationForAnalysis', models.TextField(verbose_name='Подготовка к анализу')),
                ('requirements', models.TextField(verbose_name='Требования')),
                ('interpretationOfResults', models.TextField(verbose_name='Интерпретация результатов')),
                ('laboratoryTest', models.CharField(max_length=500, verbose_name='Лабораторные тесты')),
                ('biomaterial', models.TextField(verbose_name='Биоматериал')),
                ('deadlineDateOfIssueOfResults', models.CharField(max_length=300, verbose_name='срок выполнения день, выдачи результатов')),
                ('price', models.IntegerField(null=True, verbose_name='Цена')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='analyze.category')),
            ],
            options={
                'verbose_name': 'Анализ',
                'verbose_name_plural': 'Анализы',
            },
        ),
    ]
