# Generated by Django 4.0.3 on 2022-03-30 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0001_initial'),
        ('analyze', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceAnalyzeToLaboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('analyze', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='analyze.analyze')),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices_lab', to='laboratory.laboratory')),
            ],
            options={
                'verbose_name': 'Цена',
                'verbose_name_plural': 'Цены',
            },
        ),
    ]
