# Generated by Django 4.0.3 on 2022-03-30 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0002_priceanalyzetolaboratory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyze',
            name='price',
        ),
    ]
